export const ADD_RESERVATION = "ADD_RESERVATION";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const SET_ACTION_FLAG = "SET_ACTION_FLAG";
export const SET_STATE_FLAG = "SET_STATE_FLAG";
export const RESERVATION_UPDATED = "RESERVATION_UPDATED";
export const SET_FILTER_DATE = "SET_FILTER_DATE";

export const FINISHED_STATE = "FINISHED_STATE";
// export const DELETE_RESERVATION = "DELETE_RESERVATION";
